version: "2"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: 192.168.99.100:2181
      KAFKA_CREATE_TOPICS: "HelloKafkaTopic:1:1"
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  java-consumer:
    build:
      context: .
      dockerfile: Dockerfile-consumer
    depends_on:
      - kafka
    tty: true
  java-producer:
    build:
      context: .
      dockerfile: Dockerfile-producer
    depends_on:
      - kafka
    tty: true
